rootProject.name = "pulse-map"
include("map-cli")
include("mapd")
include("ha-client")
include("manifest")
include("gen-proto")
include("gen-jvm")
include("gen-attrs")
include("grpc-api")
include("test-fixtures")
include("integration-tests")