name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Validate Gradle wrapper for PRs, but don't block CI on network flakiness
      - name: Validate Gradle Wrapper
        if: github.event_name == 'pull_request'
        uses: gradle/wrapper-validation-action@v2
        continue-on-error: true
        timeout-minutes: 3

      # Ensure wrapper is executable (avoids 'Permission denied')
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle (with caching)
        uses: gradle/actions/setup-gradle@v3

      - name: Spotless check
        run: ./gradlew spotlessCheck --no-daemon

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/test-results/test
            **/build/reports/tests/test
          if-no-files-found: ignore
